// Generates TypeScript types from the API's OpenAPI schema: the models its routes take
// and return.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "../..");
const out = "ucbc-web/src/api.gen.ts";

// The app is only built, not started, so no database or blob store is needed.
const openapi = JSON.parse(
  execFileSync(
    "uv",
    [
      "run",
      "-q",
      "python",
      "-c",
      "import json; from api.api import create_app; print(json.dumps(create_app().openapi()))",
    ],
    { cwd: root, encoding: "utf8" },
  ),
);

/** OpenAPI points at `#/components/schemas/X`; under one bundle those are `#/$defs/X`.
 * Pydantic titles every field, which json2ts would turn into an alias per field
 * (`Id1`, `Name5`), so only the models keep theirs. */
function clean(schema) {
  if (Array.isArray(schema)) return schema.map(clean);
  if (typeof schema !== "object" || schema === null) return schema;
  return Object.fromEntries(
    Object.entries(schema)
      .filter(([k]) => k !== "title")
      .map(([k, v]) => [k, k === "$ref" ? v.replace("#/components/schemas/", "#/$defs/") : clean(v)]),
  );
}

// Every schema as a property of one root, so each is emitted once under its own name.
const defs = Object.fromEntries(
  Object.entries(openapi.components.schemas).map(([name, s]) => [name, { ...clean(s), title: name }]),
);
const properties = Object.fromEntries(Object.keys(defs).map((k) => [k, { $ref: `#/$defs/${k}` }]));
const schema = {
  title: "Api",
  type: "object",
  properties,
  required: Object.keys(properties),
  additionalProperties: false,
  $defs: defs,
};

const ts = await compile(schema, "Api", {
  bannerComment: "// Generated by `make api-types`. Do not edit.",
  additionalProperties: false,
  unknownAny: true,
  style: { singleQuote: false },
});
writeFileSync(resolve(root, out), ts);
console.log(`wrote ${out}`);
