"""Generated by `ucbc-dev gen-sdk` from the Rust types of the `ucbc2027` game. Do not edit."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Self

from ucbc.handle import Handle


class Environment(str, Enum):
    EMPTY = "Empty"
    WALL = "Wall"


@dataclass(frozen=True)
class ItemPlayer:
    team: int

    @classmethod
    def _from(cls, d: dict[str, Any]) -> Self:
        return cls(
            team=d["team"],
        )


Item = ItemPlayer


def _from_Item(d: dict[str, Any]) -> Item:
    match d["type"]:
        case "player":
            return ItemPlayer._from(d)
    raise ValueError(f"unknown Item type {d['type']!r}")


class Ucbc2027Api(Handle):
    """Queries and actions of the `ucbc2027` game, one method each."""

    def item(self, x: int, y: int) -> Item | None:
        reply = self._query({"type": "item", "x": x, "y": y})
        return None if reply is None else _from_Item(reply)

    def environment(self, x: int, y: int) -> Environment:
        return Environment(self._query({"type": "environment", "x": x, "y": y}))

    def width(self) -> int:
        reply: int = self._query({"type": "width"})
        return reply

    def height(self) -> int:
        reply: int = self._query({"type": "height"})
        return reply

    def noop(self) -> None:
        self._act({"type": "noop"})
