// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Vec3 {
    #[prost(float, tag="1")]
    pub x: f32,
    #[prost(float, tag="2")]
    pub y: f32,
    #[prost(float, tag="3")]
    pub z: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Entity {
    #[prost(uint64, tag="1")]
    pub id: u64,
    #[prost(message, optional, tag="2")]
    pub position: ::core::option::Option<Vec3>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameState {
    #[prost(message, repeated, tag="1")]
    pub entities: ::prost::alloc::vec::Vec<Entity>,
    #[prost(uint64, tag="2")]
    pub tick: u64,
}
// @@protoc_insertion_point(module)
