"""Generated by `ucbc-dev gen-sdk` from the Rust types of the `ucbc2027` game. Do not edit."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Self

from ucbc.handle import Handle


@dataclass(frozen=True)
class State:
    """How many ticks have ended this set."""

    tick: int

    @classmethod
    def _from(cls, d: dict[str, Any]) -> Self:
        return cls(
            tick=d["tick"],
        )


class Ucbc2027Api(Handle):
    """Queries and actions of the `ucbc2027` game, one method each."""

    def state(self) -> State:
        """The game state."""
        return State._from(self._query({"type": "state"}))

    def noop(self) -> None:
        """Does nothing."""
        self._act({"type": "noop"})
