// Generated by `make viewer-types`. Do not edit.

/**
 * One team, one code submission. Fixed for the whole match.
 */
export type TeamId = number;
/**
 * How a set ended.
 */
export type Reason = "win" | "draw" | "forfeit";
/**
 * One unit the game asks to step. Ids are assigned by the game, unique within a set.
 */
export type BotId = number;

export interface Replay {
  config: MatchConfig;
  engine_version: string;
  match_id: string;
  result: MatchResult;
  sets: SetReplay[];
  teams: TeamInfo[];
}
export interface MatchConfig {
  /**
   * Registry key of the game, e.g. `"tictactoe"`.
   */
  game: string;
  /**
   * Opaque to the engine; handed to the game factory.
   */
  game_config?: unknown;
  limits: BotResourceLimit;
  /**
   * A set still in progress after this many ticks ends as a draw.
   */
  max_ticks?: number;
  seed: number;
  /**
   * Number of sets. The first team rotates each set.
   */
  sets: number;
  /**
   * Number of teams. Must equal the number of team specs.
   */
  teams: number;
}
/**
 * What each bot may use.
 */
export interface BotResourceLimit {
  /**
   * Bytes the bot's runtime may hold.
   */
  memory_bytes: number;
  /**
   * Budget for loading the team's code and for each step, in milliseconds of the
   * bot's own clock. For Python bots that clock counts instructions, one a
   * nanosecond, so it reads the same on every machine.
   */
  step_ms: number;
}
export interface MatchResult {
  /**
   * Sets won, indexed by team.
   */
  set_wins: number[];
  sets: SetResult[];
  /**
   * `None` when the top score is shared.
   */
  winner_team?: TeamId | null;
}
export interface SetResult {
  detail?: string;
  first_team: TeamId;
  index: number;
  reason: Reason;
  /**
   * Number of ticks played.
   */
  ticks: number;
  /**
   * `None` is a draw.
   */
  winner_team?: TeamId | null;
}
export interface SetReplay {
  first_team: TeamId;
  index: number;
  initial_state: unknown;
  result: SetResult;
  ticks: Tick[];
}
export interface Tick {
  /**
   * 0-based within the set.
   */
  number: number;
  /**
   * Game snapshot after the tick.
   */
  state_after: unknown;
  steps: Step[];
}
export interface Step {
  /**
   * Accepted actions only, in order.
   */
  actions: unknown[];
  bot: BotId;
  failure?: FailureRecord | null;
  stdout?: string;
  team: TeamId;
  usage: Usage;
}
/**
 * Attached to the step where a bot's runtime failed.
 */
export interface FailureRecord {
  kind: string;
  message: string;
  traceback?: string;
}
/**
 * What a step used.
 */
export interface Usage {
  /**
   * Bytes the bot's runtime held after the step; absent when the runtime cannot tell.
   */
  memory?: number | null;
  /**
   * What the bot's runtime charged the step. For Python bots that is instructions
   * at a nanosecond each, the same count on every machine.
   */
  time_us: number;
}
export interface TeamInfo {
  id: TeamId;
  name: string;
}
