// Generates TypeScript types from the engine's JSON Schemas: the replay format, and each
// game's snapshot and action. `--check` fails instead of writing when a file is stale.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "../..");
const games = { tictactoe: "ucbc-tictactoe/viewer/src/api.gen.ts" };
const check = process.argv.includes("--check");

const options = {
  bannerComment: "// Generated by `make viewer-types`. Do not edit.",
  additionalProperties: false,
  unknownAny: true,
  style: { singleQuote: false },
};

function devCli(...args) {
  const out = execFileSync("cargo", ["run", "-q", "-p", "ucbc-dev", "--", ...args], {
    cwd: root,
    encoding: "utf8",
  });
  return JSON.parse(out);
}

/** schemars writes a documented `serde_json::Value` as `{description}`, which json2ts
 * reads as an object; it is any JSON value. */
function anyValues(schema) {
  if (Array.isArray(schema)) return schema.map(anyValues);
  if (typeof schema !== "object" || schema === null) return schema;
  const keys = Object.keys(schema);
  if (keys.length > 0 && keys.every((k) => k === "description" || k === "default")) {
    return { ...schema, tsType: "unknown" };
  }
  return Object.fromEntries(Object.entries(schema).map(([k, v]) => [k, anyValues(v)]));
}

/** One schema whose `$defs` hold the named schemas, so shared types are emitted once. */
function bundle(title, schemas) {
  const defs = {};
  const properties = {};
  for (const [key, { $defs, $schema, ...schema }] of Object.entries(schemas)) {
    Object.assign(defs, $defs);
    defs[schema.title] = schema;
    properties[key] = { $ref: `#/$defs/${schema.title}` };
  }
  return { title, type: "object", properties, required: Object.keys(properties), $defs: defs };
}

const outputs = { "ucbc-viewer/src/replay.gen.ts": devCli("replay-schema") };
for (const [game, path] of Object.entries(games)) {
  const api = devCli("api", game);
  outputs[path] = bundle(`${api.type_name}Api`, { snapshot: api.snapshot, action: api.action });
}

let stale = false;
for (const [path, schema] of Object.entries(outputs)) {
  const ts = await compile(anyValues(schema), schema.title, options);
  const file = resolve(root, path);
  if (!check) {
    writeFileSync(file, ts);
    console.log(`wrote ${path}`);
  } else if (!existsSync(file) || readFileSync(file, "utf8") !== ts) {
    console.error(`${path} is out of date; run \`make viewer-types\``);
    stale = true;
  }
}
process.exit(stale ? 1 : 0);
