// Generated by `make api-types`. Do not edit.

export interface Api {
  Body_upload_submissions_post: BodyUploadSubmissionsPost;
  Credentials: Credentials;
  HTTPValidationError: HTTPValidationError;
  Match: Match;
  "MatchConfig-Input": MatchConfigInput;
  "MatchConfig-Output": MatchConfigOutput;
  MatchCreated: MatchCreated;
  MatchEnqueue: MatchEnqueue;
  MatchRow: MatchRow;
  MyTeam: MyTeam;
  SetResult: SetResult;
  Submission: Submission;
  TeamCreate: TeamCreate;
  TeamElo: TeamElo;
  TeamInfo: TeamInfo;
  TeamJoin: TeamJoin;
  User: User;
  UserCreate: UserCreate;
  ValidationError: ValidationError;
}
export interface BodyUploadSubmissionsPost {
  file: string;
  game: string;
  name?: string | null;
}
export interface Credentials {
  email: string;
  password: string;
}
export interface HTTPValidationError {
  detail?: ValidationError[];
}
export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {};
}
/**
 * A match with its set results.
 */
export interface Match {
  id: string;
  origin: "user" | "platform";
  game: string;
  engine_version: string | null;
  teams: TeamInfo[];
  config: MatchConfigOutput;
  bots: string[];
  status: "queued" | "running" | "done" | "error";
  set_wins: number[] | null;
  winner_team: number | null;
  error: string | null;
  priority: number;
  attempts: number;
  max_attempts: number;
  claimed_by: string | null;
  claimed_at: string | null;
  heartbeat_at: string | null;
  created_at: string;
  completed_at: string | null;
  sets: SetResult[];
}
export interface TeamInfo {
  id: number;
  name: string;
}
/**
 * What `ucbc run` is told; the defaults are its own. The API does not import the engine.
 */
export interface MatchConfigOutput {
  sets: number;
  seed: number;
  step_ms: number;
  memory_bytes: number;
}
export interface SetResult {
  index: number;
  first_team: number;
  winner_team: number | null;
  reason: "win" | "draw" | "forfeit";
  detail: string;
  ticks: number;
}
/**
 * What `ucbc run` is told; the defaults are its own. The API does not import the engine.
 */
export interface MatchConfigInput {
  sets?: number;
  seed?: number;
  step_ms?: number;
  memory_bytes?: number;
}
export interface MatchCreated {
  id: string;
}
/**
 * A match for a worker to play.
 */
export interface MatchEnqueue {
  game: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  bots: [string, string];
  config?: MatchConfigInput1;
  priority?: number;
}
/**
 * What `ucbc run` is told; the defaults are its own. The API does not import the engine.
 */
export interface MatchConfigInput1 {
  sets?: number;
  seed?: number;
  step_ms?: number;
  memory_bytes?: number;
}
/**
 * A `matches` row.
 */
export interface MatchRow {
  id: string;
  origin: "user" | "platform";
  game: string;
  engine_version: string | null;
  teams: TeamInfo[];
  config: MatchConfigOutput;
  bots: string[];
  status: "queued" | "running" | "done" | "error";
  set_wins: number[] | null;
  winner_team: number | null;
  error: string | null;
  priority: number;
  attempts: number;
  max_attempts: number;
  claimed_by: string | null;
  claimed_at: string | null;
  heartbeat_at: string | null;
  created_at: string;
  completed_at: string | null;
}
/**
 * The caller's team with its members' display names.
 */
export interface MyTeam {
  id: number;
  name: string;
  join_code: string;
  created_at: string;
  members: string[];
}
/**
 * A `submissions` row with its uploader's display name and its team's name, which is
 * how the repo always reads one.
 */
export interface Submission {
  id: string;
  user_id: number;
  team_id: number;
  name: string;
  game: string;
  size: number;
  sha256: string;
  created_at: string;
  display_name: string;
  team_name: string;
}
export interface TeamCreate {
  name: string;
}
/**
 * A team's rating, rounded, and how many matches moved it. Anyone may read it.
 */
export interface TeamElo {
  id: number;
  name: string;
  elo: number;
  matches: number;
}
export interface TeamJoin {
  code: string;
}
/**
 * The caller's own user. It carries an email, so it is should not be returned for anyone
 * else.
 */
export interface User {
  id: number;
  email: string;
  display_name: string;
  is_admin: boolean;
  team_id: number;
  created_at: string;
}
/**
 * Self-serve signup. Admins are made with `ucbc-api-cli create-admin`.
 */
export interface UserCreate {
  email: string;
  display_name: string;
  password: string;
}
