// Generated by `make viewer-types`. Do not edit.

export type Cell = "empty" | "x" | "o";
export type Action = {
  col: number;
  row: number;
  type: "place";
};

export interface TicTacToeApi {
  snapshot: Board;
  action: Action;
}
/**
 * 3x3 board, row-major.
 */
export interface Board {
  /**
   * @minItems 9
   * @maxItems 9
   */
  cells: [Cell, Cell, Cell, Cell, Cell, Cell, Cell, Cell, Cell];
}
