"""Generated by `ucbc-dev gen-sdk` from the Rust types of the `tictactoe` game. Do not edit."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Self

from ucbc.handle import Handle


@dataclass(frozen=True)
class BoardView:
    """What a bot sees when it asks for the board."""

    cells: list[Cell]
    you: Cell
    """The mark this bot plays."""
    to_move: Cell
    turn: int
    """Marks placed so far this set."""

    @classmethod
    def _from(cls, d: dict[str, Any]) -> Self:
        return cls(
            cells=[Cell(v) for v in d["cells"]],
            you=Cell(d["you"]),
            to_move=Cell(d["to_move"]),
            turn=d["turn"],
        )


class Cell(str, Enum):
    EMPTY = "empty"
    X = "x"
    O = "o"


@dataclass(frozen=True)
class Placed:
    """The mark that was placed."""

    row: int
    col: int
    mark: Cell

    @classmethod
    def _from(cls, d: dict[str, Any]) -> Self:
        return cls(
            row=d["row"],
            col=d["col"],
            mark=Cell(d["mark"]),
        )


class TicTacToeApi(Handle):
    """Queries and actions of the `tictactoe` game, one method each."""

    def board(self) -> BoardView:
        """The board and whose turn it is."""
        return BoardView._from(self._query({"type": "board"}))

    def place(self, row: int, col: int) -> Placed:
        """Place this bot's mark. Refused if the cell is taken or a mark was already
        placed this step."""
        return Placed._from(self._act({"type": "place", "row": row, "col": col}))
