// @generated by protoc-gen-es v2.16.0 with parameter "target=ts"
// @generated from file map.proto (package ucbc2027, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file map.proto.
 */
export const file_map: GenFile = /*@__PURE__*/
  fileDesc("CgltYXAucHJvdG8SCHVjYmMyMDI3IkMKA01hcBINCgV3aWR0aBgBIAEoDRIOCgZoZWlnaHQYAiABKA0SHQoFdGlsZXMYAyADKAsyDi51Y2JjMjAyNy5UaWxlIlAKBFRpbGUSKgoLZW52aXJvbm1lbnQYASABKA4yFS51Y2JjMjAyNy5FbnZpcm9ubWVudBIcCgRpdGVtGAIgASgOMg4udWNiYzIwMjcuSXRlbSpPCgtFbnZpcm9ubWVudBIVChFFTlZJUk9OTUVOVF9FTVBUWRAAEhQKEEVOVklST05NRU5UX1dBTEwQARITCg9FTlZJUk9OTUVOVF9MQUIQAiomCgRJdGVtEg0KCUlURU1fTk9ORRAAEg8KC0lURU1fRk9TU0lMEAFiBnByb3RvMw");

/**
 * 0, 0 is top left
 *
 * @generated from message ucbc2027.Map
 */
export type Map = Message<"ucbc2027.Map"> & {
  /**
   * @generated from field: uint32 width = 1;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 2;
   */
  height: number;

  /**
   * tile (x, y) is `tiles[y * width + x]`.
   *
   * @generated from field: repeated ucbc2027.Tile tiles = 3;
   */
  tiles: Tile[];
};

/**
 * Describes the message ucbc2027.Map.
 * Use `create(MapSchema)` to create a new message.
 */
export const MapSchema: GenMessage<Map> = /*@__PURE__*/
  messageDesc(file_map, 0);

/**
 * what the tile is made of, and what lies on it when the set starts
 *
 * @generated from message ucbc2027.Tile
 */
export type Tile = Message<"ucbc2027.Tile"> & {
  /**
   * @generated from field: ucbc2027.Environment environment = 1;
   */
  environment: Environment;

  /**
   * @generated from field: ucbc2027.Item item = 2;
   */
  item: Item;
};

/**
 * Describes the message ucbc2027.Tile.
 * Use `create(TileSchema)` to create a new message.
 */
export const TileSchema: GenMessage<Tile> = /*@__PURE__*/
  messageDesc(file_map, 1);

/**
 * fixed for the whole set
 *
 * @generated from enum ucbc2027.Environment
 */
export enum Environment {
  /**
   * @generated from enum value: ENVIRONMENT_EMPTY = 0;
   */
  EMPTY = 0,

  /**
   * @generated from enum value: ENVIRONMENT_WALL = 1;
   */
  WALL = 1,

  /**
   * a lab is a 2x2 square of these; the first in reading order is team 0's
   *
   * @generated from enum value: ENVIRONMENT_LAB = 2;
   */
  LAB = 2,
}

/**
 * Describes the enum ucbc2027.Environment.
 */
export const EnvironmentSchema: GenEnum<Environment> = /*@__PURE__*/
  enumDesc(file_map, 0);

/**
 * @generated from enum ucbc2027.Item
 */
export enum Item {
  /**
   * @generated from enum value: ITEM_NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: ITEM_FOSSIL = 1;
   */
  FOSSIL = 1,
}

/**
 * Describes the enum ucbc2027.Item.
 */
export const ItemSchema: GenEnum<Item> = /*@__PURE__*/
  enumDesc(file_map, 1);

