// Generated by `make viewer-types`. Do not edit.

export type Environment = "Empty" | "Wall";
export type Item = {
  team: number;
  type: "player";
};
export type Action = {
  type: "noop";
};

export interface Ucbc2027Api {
  snapshot: State;
  action: Action;
}
export interface State {
  board: Tile[][];
  tick: number;
}
export interface Tile {
  environment: Environment;
  item?: Item | null;
}
