// Generated by `make viewer-types`. Do not edit.

export type Environment = "Empty" | "Wall";
export type Item = "Player";
export type Action = {
  type: "noop";
};

export interface Ucbc2027Api {
  snapshot: State;
  action: Action;
}
/**
 * How many ticks have ended this set.
 */
export interface State {
  board: Tile[][];
}
export interface Tile {
  environment: Environment;
  item?: Item | null;
}
