// Generated by `make viewer-types`. Do not edit.

/**
 * What a tile is made of. Fixed for the whole set.
 */
export type Environment =
  | {
      type: "empty";
    }
  | {
      type: "wall";
    }
  | {
      team: number;
      type: "lab";
    };
/**
 * A bot as it sees itself.
 */
export type UnitEntry = {
  id: number;
  team: number;
} & UnitEntry1;
export type UnitEntry1 =
  | {
      health: number;
      origin: Coord1;
      type: "lab";
    }
  | {
      health: number;
      held?: ItemView | null;
      level: number;
      pos: Coord;
      type: "dino";
    };
/**
 * What is on a tile.
 */
export type ItemView =
  | {
      level: number;
      team: number;
      type: "dino";
    }
  | {
      type: "fossil";
    };
export type Action =
  | {
      type: "noop";
    }
  | {
      type: "spawn";
      x: number;
      y: number;
    };

export interface Ucbc2027Api {
  snapshot: Snapshot;
  action: Action;
}
/**
 * The whole set after a tick.
 */
export interface Snapshot {
  /**
   * Rows of tiles, `environment[y][x]`.
   */
  environment: Environment[][];
  /**
   * Fossils lying on the board.
   */
  fossils: Coord[];
  /**
   * Indexed by team.
   */
  teams: TeamView[];
  tick: number;
  /**
   * Live bots in step order.
   */
  units: UnitEntry[];
}
/**
 * A tile: `x` grows to the right, `y` downward.
 */
export interface Coord {
  x: number;
  y: number;
}
export interface TeamView {
  bones: number;
}
/**
 * A tile: `x` grows to the right, `y` downward.
 */
export interface Coord1 {
  x: number;
  y: number;
}
